import {ApiService} from './services/ApiService.js';
export const todayISO=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
export function fieldMessage(name,value,checked=false){if(name==='consent')return checked?'':'Нужно согласие на обработку данных.';if(!value.trim())return 'Заполните это поле.';if(name==='name'&&value.trim().length<2)return 'Укажите имя — минимум 2 символа.';if(name==='email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))return 'Введите корректный email.';if(name==='phone'&&(!/^[+\d\s().-]+$/.test(value)||value.replace(/\D/g,'').length<7||value.replace(/\D/g,'').length>15))return 'Укажите телефон: от 7 до 15 цифр.';if(name==='plan'&&!['day','month','team','tour'].includes(value))return 'Выберите тариф.';if(name==='date'){const parsed=new Date(`${value}T12:00:00`);if(!/^\d{4}-\d{2}-\d{2}$/.test(value)||!Number.isFinite(parsed.getTime())||parsed.getFullYear()!==Number(value.slice(0,4))||parsed.getMonth()+1!==Number(value.slice(5,7))||parsed.getDate()!==Number(value.slice(8,10)))return 'Выберите корректную дату.';if(value<todayISO())return 'Дата визита не может быть в прошлом.'}return ''}
export function validateForm(form){let first=null;for(const input of form.querySelectorAll('input,select')){const message=fieldMessage(input.name,input.value,input.checked);const error=document.querySelector('#'+input.id+'-error');if(error){error.textContent=message;input.setAttribute('aria-invalid',String(!!message));input.setAttribute('aria-describedby',error.id)}if(message&&!first)first=input}first?.focus();return !first}
export class BookingPanel {
 constructor({getPlan,getZone}){
  this.getPlan=getPlan;this.getZone=getZone;this.abort=new AbortController();
  this.dialog=document.querySelector('#booking-dialog');this.form=document.querySelector('#booking-form');this.api=new ApiService();
  const on=(target,event,handler)=>target.addEventListener(event,handler,{signal:this.abort.signal});
  document.querySelector('#book-date').min=todayISO();
  on(this.dialog.querySelector('.close-dialog'),'click',()=>this.close());
  on(this.dialog.querySelector('.close-success'),'click',()=>this.close());
  on(this.dialog,'click',e=>{const r=this.dialog.getBoundingClientRect();if(e.target===this.dialog&&(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom))this.close();});
  on(this.dialog,'close',()=>{document.body.style.overflow='';this.opener?.focus();});
  on(this.form,'submit',e=>this.submit(e));on(document.querySelector('#download-request'),'click',()=>this.download());
 }
 open({kind,name='',email='',opener=document.activeElement}={}){this.opener=opener;this.form.reset();this.form.querySelectorAll('[aria-invalid]').forEach(el=>el.removeAttribute('aria-invalid'));this.dialog.querySelectorAll('.field-error').forEach(el=>el.textContent='');document.querySelector('#booking-success').hidden=true;document.querySelector('#booking-content').hidden=false;this.zone=kind==='tour'?null:this.getZone();let plan=this.getPlan();if(this.zone&&!this.zone.plans.includes(plan))plan=this.zone.plans[0];document.querySelector('#book-plan').value=kind==='tour'?'tour':plan;document.querySelector('#book-name').value=name;document.querySelector('#book-email').value=email;document.querySelector('#book-date').min=todayISO();document.querySelector('#book-date').value=todayISO();document.querySelector('#booking-title').textContent=kind==='tour'?'Познакомимся с местом.':'Запланируем визит.';document.querySelector('#booking-zone').textContent=this.zone?'Зона: '+this.zone.name:'Выберем подходящее место вместе.';if(!this.dialog.open)this.dialog.showModal();document.body.style.overflow='hidden';document.querySelector('#book-name').focus()}
 close(){if(this.dialog.dataset.animated==='true')this.dialog.dispatchEvent(new Event('freespace:request-close'));else this.dialog.close()}
 async submit(e){e.preventDefault();if(!validateForm(this.form))return;const button=this.form.querySelector('[type=submit]');button.disabled=true;button.textContent='Сохраняем…';document.querySelector('#submit-error').textContent='';try{const data=Object.fromEntries(new FormData(this.form));data.zone=this.zone?.id||null;data.consent=true;const result=await this.api.saveRequest(data);this.saved=result.data;document.querySelector('#booking-content').hidden=true;document.querySelector('#booking-success').hidden=false;document.querySelector('#success-summary').textContent=`${data.name}, ${new Date(data.date+'T12:00:00').toLocaleDateString('ru-RU')} · ${this.form.elements.plan.selectedOptions[0].textContent}${this.zone?' · '+this.zone.name:''}`;document.querySelector('#download-request').focus()}catch(error){document.querySelector('#submit-error').textContent=error.message}finally{button.disabled=false;button.textContent='Сохранить заявку'}}
 download(){if(!this.saved)return;const blob=new Blob([JSON.stringify(this.saved,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='freespace-request.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 destroy(){this.abort.abort();if(this.dialog.open)this.dialog.close();document.body.style.overflow='';}
}
