import {zones,plans} from './js/data.js';
import {FallbackPlan} from './js/FallbackPlan.js';
import {BookingPanel,validateForm} from './js/BookingPanel.js';
let scene=null,selected=null,currentPlan='day';
const fallback=new FallbackPlan(document.querySelector('#fallback'),zones,selectZone);
const shortcuts=document.querySelector('#zone-shortcuts');
shortcuts.innerHTML=zones.map(z=>`<button style="--zone-color:${z.color}" data-zone-id="${z.id}" aria-pressed="false" aria-label="${z.name}: ${z.shared?'общая зона':z.free+' свободно из '+z.total}">${z.name}</button>`).join('');
document.querySelector('#zone-list').innerHTML=zones.map((z,i)=>`<article class="zone-tile" id="zone-${z.id}" style="--zone-color:${z.color}"><div class="zone-tile-top"><span class="zone-symbol" aria-hidden="true">${z.symbol}</span><h3>${z.name}</h3><span class="zone-number">0${i+1}</span></div><p>${z.description}</p><div class="zone-tile-footer"><span>${z.shared?'Для всех резидентов':z.free?'Свободно: '+z.free+' / '+z.total:'Сейчас занято'}</span><button data-zone-id="${z.id}" aria-label="Подробнее: ${z.name}">Посмотреть</button></div></article>`).join('');
function selectZone(id){selected=zones.find(z=>z.id===id);if(!selected)return;fallback.highlight(id);scene?.select(id);document.querySelectorAll('[data-zone-id]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.zoneId===id)));document.querySelectorAll('.zone-tile').forEach(el=>el.classList.toggle('selected',el.id==='zone-'+id));const detail=document.querySelector('#zone-detail');detail.innerHTML=`<button data-close-zone aria-label="Закрыть описание">×</button><h3>${selected.name}</h3><p>${selected.description}</p><small>${selected.shared?'Включено в каждый тариф':selected.free?'Свободно '+selected.free+' из '+selected.total:'Сейчас все места заняты'}</small><button class="button" data-book ${!selected.free&&!selected.shared?'disabled':''}>${selected.shared?'Выбрать тариф':selected.free?'Выбрать место':'Сейчас занято'}</button>`;detail.hidden=false}
function choosePlan(id){if(!plans[id])return;if(selected&&!selected.plans.includes(id)){selected=null;document.querySelector("#zone-detail").hidden=true;document.querySelectorAll("[data-zone-id]").forEach(b=>b.setAttribute("aria-pressed","false"));document.querySelectorAll(".zone-tile").forEach(el=>el.classList.remove("selected"));fallback.highlight(null);scene?.reset()}currentPlan=id;document.querySelectorAll('[data-plan]').forEach(b=>{const active=b.dataset.plan===id;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1});const p=plans[id],panel=document.querySelector('#price-panel');panel.setAttribute('aria-labelledby','tab-'+id);panel.innerHTML=`<div class="price-intro"><span class="price-label">${p.label}</span><div class="price-value">${p.price}<small>${p.unit}</small></div><p>${p.description}</p><button class="button" data-book>Выбрать тариф «${p.name}»</button></div><ul class="price-features">${p.features.map(f=>`<li>${f}</li>`).join('')}</ul>`;fallback.filter(id);scene?.filter(id)}
choosePlan('day');
document.addEventListener('click',e=>{const zone=e.target.closest('[data-zone-id]');if(zone){selectZone(zone.dataset.zoneId);return}const plan=e.target.closest('[data-plan]');if(plan)choosePlan(plan.dataset.plan);if(e.target.closest('[data-close-zone]'))document.querySelector('#zone-detail').hidden=true;const light=e.target.closest('[data-light]');if(light){document.querySelectorAll('[data-light]').forEach(b=>b.setAttribute('aria-pressed',String(b===light)));fallback.setLight(light.dataset.light);scene?.setLight(light.dataset.light)}const view=e.target.closest('[data-view]');if(view){fallback.setView(view.dataset.view);scene?.setView(view.dataset.view)}if(e.target.closest('[data-reset]')){fallback.setView('iso');scene?.reset();document.querySelector('#zone-detail').hidden=true}});
shortcuts.addEventListener('focusin',e=>{const id=e.target.dataset.zoneId;if(id){fallback.highlight(id);scene?.highlight(id)}});
document.querySelector('.menu-toggle').addEventListener('click',e=>{const open=e.currentTarget.getAttribute('aria-expanded')!=='true';e.currentTarget.setAttribute('aria-expanded',String(open));document.querySelector('#navigation').classList.toggle('open',open)});
document.querySelectorAll('#navigation a').forEach(a=>a.addEventListener('click',()=>{document.querySelector('#navigation').classList.remove('open');document.querySelector('.menu-toggle').setAttribute('aria-expanded','false')}));
document.querySelector('.pricing-tabs').addEventListener('keydown',e=>{const buttons=[...document.querySelectorAll('[data-plan]')];let i=buttons.indexOf(document.activeElement);if(e.key==='ArrowRight')i=(i+1)%3;else if(e.key==='ArrowLeft')i=(i+2)%3;else if(e.key==='Home')i=0;else if(e.key==='End')i=2;else return;e.preventDefault();choosePlan(buttons[i].dataset.plan);buttons[i].focus()});
document.querySelector('#year').textContent=new Date().getFullYear();
const booking=new BookingPanel({getPlan:()=>currentPlan,getZone:()=>selected});
document.addEventListener('click',e=>{const button=e.target.closest('[data-book]');if(button&&!button.disabled)booking.open({kind:button.dataset.kind,opener:button})});
document.querySelector('#tour-form').addEventListener('submit',e=>{e.preventDefault();if(validateForm(e.currentTarget)){const data=new FormData(e.currentTarget);booking.open({kind:'tour',name:data.get('name'),email:data.get('email'),opener:e.currentTarget.querySelector('button')})}});
const quotes=[{text:'«Самое ценное — возможность работать в своём темпе. Здесь легко сосредоточиться и так же легко найти собеседника за кофе».',name:'Анна К.',role:'Продуктовый дизайнер',initials:'АК'},{text:'«Команда собирается за одним столом, а для важных разговоров есть отдельная комната. Вся работа в одном месте».',name:'Марк Д.',role:'Основатель небольшой команды',initials:'МД'},{text:'«Дома всё время отвлекался. Теперь прихожу в тихую зону, закрываю задачи и ухожу домой с лёгкой головой».',name:'Денис С.',role:'Frontend-разработчик',initials:'ДС'}];let quoteIndex=0;document.querySelectorAll('[data-quote]').forEach(b=>b.addEventListener('click',()=>{quoteIndex=(quoteIndex+(b.dataset.quote==='next'?1:quotes.length-1))%quotes.length;const q=quotes[quoteIndex];document.querySelector('blockquote').textContent=q.text;document.querySelector('.quote-author strong').textContent=q.name;document.querySelector('.quote-author small').textContent=q.role+' · пример отзыва';document.querySelector('.avatar').textContent=q.initials}));
// Ленивая инициализация. На телефонах и слабых устройствах остаётся интерактивная схема.
const sceneElement=document.querySelector('#scene');let sceneStarted=false;
const observer=new IntersectionObserver(async entries=>{if(!entries.some(e=>e.isIntersecting)||sceneStarted)return;sceneStarted=true;observer.disconnect();if(matchMedia('(max-width:767px)').matches||(navigator.hardwareConcurrency&&navigator.hardwareConcurrency<=2))return;
 try{const {Scene3D}=await import('./js/Scene3D.js');scene=new Scene3D(sceneElement,zones,{onSelect:selectZone,onHover:(id,e)=>{const tooltip=document.querySelector('#scene-tooltip');tooltip.hidden=!id;if(id){tooltip.textContent=zones.find(z=>z.id===id).name;const r=sceneElement.getBoundingClientRect();tooltip.style.left=Math.min(e.clientX-r.left+12,r.width-150)+'px';tooltip.style.top=Math.max(e.clientY-r.top-35,0)+'px'}},onFailure:()=>{scene?.destroy();scene=null;document.querySelector('#fallback').hidden=false;document.querySelector('#scene-tooltip').hidden=true;document.querySelector('#scene-hint').textContent='Выберите зону на интерактивной схеме'}});scene.filter(currentPlan);const light=document.querySelector('[data-light][aria-pressed=true]').dataset.light;scene.setLight(light);document.querySelector('#fallback').hidden=true;if(selected)scene.select(selected.id)}catch{document.querySelector('#scene-hint').textContent='Выберите зону на интерактивной схеме'}
},{rootMargin:'150px'});observer.observe(sceneElement);
addEventListener('pagehide',e=>{if(!e.persisted){observer.disconnect();scene?.destroy();fallback.destroy()}});
// Прогрессивное улучшение: структурированный доступ к тем же выбору зоны и форме.
if(document.modelContext?.registerTool){const lifetime=new AbortController();const register=tool=>{try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifetime.signal})).catch(()=>{})}catch{}};register({name:'get_freespace_zones',description:'Read demo workspace zones and availability.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>zones.map(({id,name,free,total,shared})=>({id,name,free,total,shared:!!shared}))});register({name:'start_freespace_booking',description:'Open the booking form for a zone and plan. Does not submit or confirm a booking.',inputSchema:{type:'object',properties:{zoneId:{type:'string',enum:zones.map(z=>z.id)},plan:{type:'string',enum:Object.keys(plans)}},required:['zoneId','plan'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{if(!input||!plans[input.plan])throw new Error('Invalid plan');const zone=zones.find(z=>z.id===input.zoneId);if(!zone||(!zone.free&&!zone.shared)||!zone.plans.includes(input.plan))throw new Error('Zone unavailable for plan');choosePlan(input.plan);selectZone(zone.id);booking.open();return {formOpen:true,zoneId:zone.id,plan:input.plan}}});addEventListener('pagehide',()=>lifetime.abort(),{once:true})}

