import {createRequire} from 'node:module';import {mkdir,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const require=createRequire(import.meta.url);const {chromium}=require(process.env.FREESPACE_PLAYWRIGHT||'C:/Users/iamen/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
await mkdir('artifacts',{recursive:true});const browser=await chromium.launch({headless:true,channel:'msedge'});let results=[];
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});let errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',msg=>{if(msg.type()==='error')errors.push(msg.text())});await page.goto('http://127.0.0.1:4173',{waitUntil:'domcontentloaded'});await page.waitForSelector('#scene canvas',{timeout:15000});await page.waitForTimeout(800);assert.equal(await page.locator('#fallback').isVisible(),false);await page.screenshot({path:'artifacts/desktop.png',fullPage:true});
 const bounds=await page.locator('#scene canvas').boundingBox();let hit=false;for(let y=.35;y<.8&&!hit;y+=.08)for(let x=.2;x<.85&&!hit;x+=.08){await page.mouse.move(bounds.x+bounds.width*x,bounds.y+bounds.height*y);if(await page.locator('#scene-tooltip').isVisible()){await page.mouse.click(bounds.x+bounds.width*x,bounds.y+bounds.height*y);hit=await page.locator('#zone-detail').isVisible()}}assert.equal(hit,true,'Raycaster click must select a zone');await page.locator('[data-close-zone]').click();
 await page.locator('[data-zone-id=quiet]').first().click();assert.equal(await page.locator('#zone-detail h3').textContent(),'Тихая зона');await page.locator('[data-close-zone]').click();
 await page.locator('[data-light=day]').click();assert.equal(await page.locator('[data-light=day]').getAttribute('aria-pressed'),'true');await page.locator('[data-view=top]').first().click();await page.locator('[data-reset]').click();await page.locator('[data-light=night]').click();
 await page.locator('[data-plan=team]').click();assert.equal(await page.locator('[data-counter]').getAttribute('data-counter'),'24000');await page.locator('.hero-actions [data-book]').first().click();assert.equal(await page.locator('#booking-dialog').isVisible(),true);assert.equal(await page.locator('#book-plan').inputValue(),'team');
 await page.locator('#booking-form button[type=submit]').click();assert.equal(await page.locator('#book-name').getAttribute('aria-invalid'),'true');assert.equal(await page.locator('#book-name').evaluate(el=>el===document.activeElement),true);
 await page.locator('#book-name').fill('Тестовый посетитель');await page.locator('#book-email').fill('test@example.com');await page.locator('#book-phone').fill('+380501234567');await page.locator('#book-consent').check();await page.locator('#booking-form button[type=submit]').click();await page.locator('#booking-success').waitFor({state:'visible'});assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('freespace.requests')).length),1);await page.keyboard.press('Escape');await page.locator('#booking-dialog').waitFor({state:'hidden'});
 await page.locator('.hero-actions [data-book]').first().click();await page.mouse.click(10,10);await page.locator('#booking-dialog').waitFor({state:'hidden'});
 const downloads=[];page.on('download',d=>downloads.push(d));await page.locator('#tour-name').fill('Турист');await page.locator('#tour-email').fill('tour@example.com');await page.locator('#tour-form button').click();assert.equal(await page.locator('#book-plan').inputValue(),'tour');assert.equal(await page.locator('#book-name').inputValue(),'Турист');await page.keyboard.press('Escape');assert.deepEqual(errors,[]);results.push('Desktop: WebGL scene, zone selection, lighting, camera presets, tariffs, validation, local draft, Escape, backdrop, tour form: PASS');
 const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await mobile.goto('http://127.0.0.1:4173',{waitUntil:'domcontentloaded'});await mobile.waitForSelector('#scene canvas');assert.equal(await mobile.locator('.scene-host canvas').count(),1);assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await mobile.locator('[data-zone-id=phone]').first().click();assert.equal(await mobile.locator('#zone-detail .button').isDisabled(),true);await mobile.locator('[data-close-zone]').click();await mobile.locator('[data-view=top]').first().click();await mobile.locator('[data-view=iso]').first().click();await mobile.locator('.menu-toggle').click();assert.equal(await mobile.locator('#navigation').isVisible(),true);await mobile.locator('#navigation a[href="#pricing"]').click();assert.equal(await mobile.locator('#navigation').isVisible(),false);await mobile.screenshot({path:'artifacts/mobile.png',fullPage:true});results.push('Mobile: constrained WebGL scene and static fallback, zone selection, unavailable zone, camera presets, menu, no horizontal overflow: PASS');
 const offline=await browser.newPage({viewport:{width:1280,height:900}});await offline.route('**/Scene3D.js',route=>route.abort());await offline.goto('http://127.0.0.1:4173',{waitUntil:'domcontentloaded'});await offline.waitForSelector('#fallback svg');await offline.locator('[data-zone-id=meeting]').first().click();assert.equal(await offline.locator('#zone-detail h3').textContent(),'Переговорки');results.push('Failed Three.js import: accessible interactive fallback: PASS');
 const keyboard=await browser.newPage({viewport:{width:1280,height:900},reducedMotion:'reduce'});await keyboard.goto('http://127.0.0.1:4173',{waitUntil:'domcontentloaded'});await keyboard.locator('[data-zone-id=quiet]').first().focus();await keyboard.keyboard.press('Enter');assert.equal(await keyboard.locator('#zone-detail h3').textContent(),'Тихая зона');await keyboard.locator('[data-close-zone]').click();await keyboard.locator('[data-plan=day]').focus();await keyboard.keyboard.press('ArrowRight');assert.equal(await keyboard.locator('[data-plan=month]').getAttribute('aria-selected'),'true');results.push('Keyboard zone selection, tariff arrow keys, reduced motion: PASS');
 results.push('Native WebMCP validation: '+(await page.evaluate(()=>!!document.modelContext?.registerTool)?'available':'unavailable in this browser; progressive enhancement only'));
 await writeFile('artifacts/check-results.txt',results.join('\n')+'\n');console.log(results.join('\n'));
}finally{await browser.close()}



